services:
  db:
    image: postgres:15-alpine
    container_name: db_projeto
    restart: unless-stopped
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: projeto_db
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Admin -d projeto_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projeto_db
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    stdin_open: true
    tty: true

volumes:
  db_data: