spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.hikari.connection-init-sql=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=TRACE

jwt.secret=aldeia-saas-chave-super-secreta-2026-projeto-faculdade
jwt.expiration-ms=86400000